Use Processing-Timestamp based Gap Detection in TransactionalEventProducer
RBMHTechnology/calliope pull request #16
Opened 2017-06-29 11:27 UTC by cstub

To mitigate the risk of event-loss which might happen if multiple application nodes
with unsynchronized clocks emit events or may occur in certain situations with unusually
long CG-times, the event-timestamp based gap detection is discontinued.

Implement a processing-timestamp based gap detection which uses a batched approach
(i.e. all gaps within an event batch will be persisted at once) providing better latency
per gap.

2017-06-29 15:08 UTC, volkerstampa reviewed
Just some minor issues. I leave it up to you if you want to fix them.

2017-06-29 15:08 UTC, volkerstampa commented on src/main/scala/com/rbmhtechnology/calliope/GapDetection.scala
> +trait BatchGapDetection extends GapDetection {
I wonder, if we should document somewhere that `gapLess` and the returned function is not thread safe.

2017-06-29 15:08 UTC, volkerstampa commented on src/test/scala/com/rbmhtechnology/calliope/GapDetectionSpec.scala
> +      filterGapLess(4, events(4 to 9)) mustBe events(4 to 7)
Wouldn't it be clearer if this were `events(5 to 7)`?

2017-06-29 15:08 UTC, volkerstampa commented on src/test/scala/com/rbmhtechnology/calliope/GapDetectionSpec.scala
> +      filterGapLess(8, events(8 to 10)) mustBe events(8 to 10)
`mustBe events(9 to 10)`

2017-06-29 15:08 UTC, volkerstampa commented on src/test/scala/com/rbmhtechnology/calliope/GapDetectionSpec.scala
> +      filterGapLess(1, events(1 to 5)) mustBe events(1 to 5)
Why are these checks part of this test and why isn't it a single check `filterGapLess(1, events(1 to 10)) mustBe events(1 to 10)`

2017-06-29 15:08 UTC, volkerstampa commented on src/test/scala/com/rbmhtechnology/calliope/GapDetectionSpec.scala
> +      filterGapLess(4, events(4 to 10)) mustBe events(4 to 8)
`events(5 to 7)` instead of `4 to 8`?

2017-06-29 15:08 UTC, volkerstampa commented on src/test/scala/com/rbmhtechnology/calliope/GapDetectionSpec.scala
> +      waitForPersistTimeout()
Given we have no rounding error `sleep(timeout / 4)` should be fine, right?

2017-06-30 09:45 UTC, cstub commented on src/main/scala/com/rbmhtechnology/calliope/GapDetection.scala
> +trait BatchGapDetection extends GapDetection {
+1

2017-06-30 09:53 UTC, cstub commented on src/test/scala/com/rbmhtechnology/calliope/GapDetectionSpec.scala
> +      filterGapLess(1, events(1 to 5)) mustBe events(1 to 5)
+1 should be a single check. 
This check is part of this test bc it should illustrate that once gaps have been persisted (in previous iterations) a subsequent iteration is not delayed by the (now persisted) gaps.

2017-06-30 09:53 UTC, cstub commented on src/test/scala/com/rbmhtechnology/calliope/GapDetectionSpec.scala
> +      filterGapLess(4, events(4 to 9)) mustBe events(4 to 7)
+1

2017-06-30 09:53 UTC, cstub commented on src/test/scala/com/rbmhtechnology/calliope/GapDetectionSpec.scala
> +      filterGapLess(8, events(8 to 10)) mustBe events(8 to 10)
+1

2017-06-30 09:55 UTC, cstub commented on src/test/scala/com/rbmhtechnology/calliope/GapDetectionSpec.scala
> +      filterGapLess(4, events(4 to 10)) mustBe events(4 to 8)
+1

2017-06-30 09:57 UTC, cstub commented on src/test/scala/com/rbmhtechnology/calliope/GapDetectionSpec.scala
> +      waitForPersistTimeout()
+1 but I guess the safe bet would be to use `timeout / 2` to ensure that the whole timeout has elapsed.

2017-07-03 11:03 UTC, volkerstampa requested changes

2017-07-03 11:03 UTC, volkerstampa commented on src/test/scala/com/rbmhtechnology/calliope/GapDetectionSpec.scala
> +      waitForPersistTimeout()
But this is still an entire timeout, right? Or am I missing something?

2017-07-03 11:28 UTC, cstub commented on src/test/scala/com/rbmhtechnology/calliope/GapDetectionSpec.scala
> +      waitForPersistTimeout()
Ok, now I got it :) I will update it accordingly.

2017-07-03 11:59 UTC, volkerstampa approved these changes
+1

2017-07-03 12:32 UTC, merged